version: '1.0'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: karohost
      POSTGRES_USER: shastri
      NODE_ENV: production
    restart: always

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: karohost
      POSTGRES_USER: shastri
      POSTGRES_HOST_AUTH_METHOD: trust
      LISTEN_ADDRESSES: '*'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'db_prod']
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_data:
